site_name: pinax-referrals
pages:
- [index.md, Home]
- [installation.md, Installation]
- [settings.md, Settings]
- [signals.md, Signals]
- [templates.md, Templates]
- [templatetags.md, Template Tags]
- [usage.md, Usage]
- [migrations.md, Migrations]
- [changelog.md, Change Log]
theme: readthedocs
repo_url: https://github.com/pinax/pinax-referrals
site_description: "a referrals app for Django"
site_author: "Pinax Team"
markdown_extensions: [admonition]
